sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
matrix:
  fast_finish: true
node_js:
  - '5'
  - '6'
  - '7'
  - '8'
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
before_script:
  - 'sh -e /etc/init.d/xvfb start'
  - 'export DISPLAY=:99.0'
  - 'greenkeeper-lockfile-update'
script: npm install && npm run build
after_script:
  - 'greenkeeper-lockfile-upload'
after_success: npm run coverage
