environment:
  matrix:
      - nodejs_version: "4"
      - nodejs_version: "6"
      - nodejs_version: "7"

branches:
  only:
  - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"

build_script:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq 'master') { node ./scripts/set-dev-version.js }
  - npm run build

test_script:
  - node --version
  - npm --version
  - npm test

build: off
